[package]
name = "TypesAndVariables"
version = "0.1.0"
authors = ["Zachery Studer <zachery.j.studer@accenture.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
